name: RahasyaScan – DevSecOps Security Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  security-events: write

jobs:
  rahasyascan:
    name: Secrets & Dependency Scan
    runs-on: ubuntu-latest

    steps:
      # -------------------- CHECKOUT --------------------
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # -------------------- PULL IMAGE --------------------
      - name: Pull RahasyaScan Docker Image
        run: |
          docker pull --platform linux/amd64 aniket2003/rahasyascan:v1.1.0

      # -------------------- RUN SCAN --------------------
      - name: Run RahasyaScan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GGSHIELD_TOKEN: ${{ secrets.GGSHIELD_TOKEN }}
        run: |
          docker run --rm --platform linux/amd64 \
            -e SNYK_TOKEN \
            -e GGSHIELD_TOKEN \
            -v ${{ github.workspace }}:/repo \
            aniket2003/rahasyascan:v1.1.0 \
            -scan gitleaks gittyleaks trufflehog detect-secrets snyk

      # -------------------- UPLOAD RESULTS --------------------
      - name: Upload Security Reports
        uses: actions/upload-artifact@v5
        with:
          name: RahasyaScan-Reports
          path: |
            Secret_Detection_Reports/
          retention-days: 14
